### ISSUE TITLE
Change DNS for bit.ly

### ISSUE THREAD

**Issue by danielpetty** [denverpost/bitly#8]
Message from bit.ly:

It is important that you reconfigure your Branded Domain by June 29th, 2016 to avoid all of your links breaking. Bitly is migrating to a new world-class hosting provider with 46 data centers around the globe to make your links faster and more secure. For your links to continue working after the migration on June 29th, you will need to change your DNS settings directly with your domain provider. 

We are making this change so we can better address your growing and evolving needs. We promise you will never have to do it again!

Here is how this change benefits your business:

Significant improvement in network performance and the ability to geo-distribute our platform means getting your customers around the globe to the right place faster.

Added capability to scale our platform quickly with fast turnaround SLAs on hardware deployment means accommodating your business through every stage of growth.
No trade offs between security and performance of your links.

Please note that if you don't change your settings by June 29th, 2016, your links will unfortunately break. We apologize for the inconvenience and are fully prepared to assist with this transition.

Learn how to update your domain's DNS configuration at http://bitly.com/change-dns-settings or contact your Customer Success Manager today for additional information and guidance.

**Comment by freejoe76** [comment]
This is done.
